=== pratik006/uci-connector/server/src/main/resources/serverConfig.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="serverConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="adminPort" type="xs:int"></xs:element>
				<xs:element name="externalServerUrl" type="xs:string" default="http://prapps.net63.net/chess"></xs:element>
				<xs:element name="servers" type="server" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="protocol" type="xs:string"></xs:attribute>
			<xs:attribute name="password" type="xs:string"></xs:attribute>
			<xs:attribute name="fromMail" type="xs:string"></xs:attribute>
			<xs:attribute name="mailPass" type="xs:string"></xs:attribute>
			<xs:attribute name="toMail" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="server">
		<xs:complexContent>
			<xs:extension base="basicServer">
				<xs:sequence>
					<xs:element name="path" type="xs:string"></xs:element>
					<xs:element name="command" type="xs:string" minOccurs="0"></xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="basicServer">
		<xs:sequence>
			<xs:element name="state" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="port" type="xs:int"></xs:attribute>
		<xs:attribute name="id" type="xs:string"></xs:attribute>
	</xs:complexType>

</xs:schema>

=== pratik006/uci-connector/serverConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<serverConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="serverConfig.xsd"
	fromMail="vickysengupta006@gmail.com" 
	mailPass="chinat0wn" 
	toMail="deepsenguptachess@gmail.com" 
	protocol="tcp" 
	password="password">
	<adminPort>11110</adminPort>
	<externalServerUrl>http://apps-pratiks.rhcloud.com/json/cs/ip</externalServerUrl>
	<servers id="houdini" name="houdini" port="11111">
		<path>/media/pratik/Backup/programming/Chess/ChessEngines/Houdini_4_Pro_x64A-v1x/Houdini_4_Pro_x64A-v1x.exe</path>
		<command>wine</command>
	</servers>	
	
	<servers id="critter" name="critter" port="11112">
		<path>/media/pratik/Backup/programming/Chess/ChessEngines//critter_1.6a_linux/critter-16a-64bit</path>
		<command></command>
	</servers>
	<servers id="stockfish" name="stockfish" port="11113">
		<path>/media/pratik/Backup/programming/Chess/ChessEngines/stockfish-dd-src/stockfish</path>
		<command></command>
	</servers>
	<servers id="komodo3" name="komodo3" port="11114">
		<path>/media/pratik/Backup/programming/Chess/ChessEngines/komodo3-linux/komodo3</path>
		<command></command>
	</servers>
	<servers id="rybka" name="komodo3" port="11115">
		<path>/media/pratik/Backup/programming/Chess/ChessEngines/Rybka_4_2/Deep Rybka 4 x64.exe</path>
		<command>wine</command>
	</servers>
	
</serverConfig>
